---
- hosts: servere
  tasks:
  - name: Install ntp deamon
    become: true
    apt:
      update_cache: true
      name: ntp
      state: present

- hosts: webserver
  become: true
  tasks:
  - name: Install pip
    apt:
      name: python-pip
      state: present
  - name: Install flask
    pip:
      name: flask
  - name: Install gunicorn
    pip:
      name: gunicorn
  - name: Checkout git repo
    git:
      repo: https://github.com/robhop/ansible-blogpost.git
      dest: /usr/local/ansible_blogpost

  - name: Start app with gunicorn with a config file
    gunicorn:
      app: 'app'
      chdir: '/usr/local/ansible_blogpost/flask_app'
      conf: '/usr/local/ansible_blogpost/flask_app/gunicorn.cfg' 

