---
- hosts: servere
  tasks:
  - name: Install ntp deamon
    become: true
    apt:
      update_cache: true
      name: ntp
      state: present

- hosts: webserver
  tasks:
  - name: Install pip
    become: true
    apt:
      name: python-pip
      state: present
  - name: Install flask
    become: true
    pip:
      name: flask
  - name: Install gunicorn
    become: true
    pip:
      name: gunicorn      

