---

# All servers is to run ntp
- hosts: servere
  tasks:
  - name: Install ntp deamon
    become: true
    apt:
      update_cache: true
      name: ntp
      state: present

# Install from github and serve our small
- hosts: webserver
  become: true
  tasks:
  - name: Install pip
    apt:
      name: python-pip
      state: present
  - name: Install flask
    pip:
      name: flask
  - name: Install gunicorn
    pip:
      name: gunicorn
  - name: Checkout git repo
    git:
      repo: https://github.com/robhop/ansible-blogpost.git
      dest: /usr/local/ansible_blogpost
  - name: Start app with gunicorn with a config file
    gunicorn:
      app: 'flask_app:app'
      chdir: '/usr/local/ansible_blogpost/flask_app'
      conf: '/usr/local/ansible_blogpost/flask_app/config.cfg' 

# Install ningx and serve the app from the webservers
- hosts: proxyserver
  become: true
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
